name: My Workflow

on:
  push:
    branches: [main]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '>=20.x'
      
      - name: Set up env file
        run: |
          touch .env
          echo "API=${{ secrets.API }}" >> .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
      
      - name: Load environment variables
        run: npm install dotenv
      - name: Install dependencies and run script
        run: |
          npm install
          npx dotenv node my-script.js
