name: My Workflow

on:
  push:
    branches: [main]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '>=20.x'
      
      - name: Set up env file
        run: |
          touch .env
          echo "API=${{ secrets.API }}" >> .env
          echo "dis=${{ secrets.dis }}" >> .env
          cat .env
      - name: Clear npm cache
        run: npm cache clean --force
  
      - name: Load environment variables
        run: npm install dotenv
      - name: Install dependencies and run script
        run: |
          npm install -g npm@7.24.2
          npm install
          npm run start

