name: Create Environment File

on:
  push:
    branches:
      - main

jobs:
  create-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up env file
        run: |
          touch .env
          echo API=${{ secrets.API }} >> .env
          echo dis=${{ secrets.dis }} >> .env
