name: My Workflow

on:
  push:
    branches: [main]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up env file
        run: |
          touch .env
          echo "API=${{ secrets.API }}" >> .env
          echo "dis=${{ secrets.dis }}" >> .env
      
      - name: Install dependencies and run script
        env:
          # Load the environment variables from the .env file using dotenv
          $(dotenv)
        run: |
          npm install
          node server.js
